# default: &default
# adapter: postgresql
# encoding: unicode
# pool: 5 # the config of size of connection pool, which is 5 by default.
#
# production:
#   <<: *default
#   database: makersbnb
#
# development:
#   <<: *default
#   database: makersbnb_dev
#
# test:
#   <<: *default
#   database: makersbnb_test

development:
  adapter: postgresql
  encoding: unicode
  database: makersbnb_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: makersbnb_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: makersbnb
  pool: 5
